import { generateCaption } from '@/lib/ai/caption-generator';

// Mock OpenAI
jest.mock('openai', () => {
    return {
        __esModule: true,
        default: jest.fn().mockImplementation(() => ({
            chat: {
                completions: {
                    create: jest.fn().mockResolvedValue({
                        choices: [
                            {
                                message: {
                                    content: 'Test caption generated by AI',
                                },
                            },
                        ],
                    }),
                },
            },
        })),
    };
});

describe('Caption Generator', () => {
    beforeEach(() => {
        jest.clearAllMocks();
    });

    it('should generate a caption successfully', async () => {
        const result = await generateCaption({
            prompt: 'Monday morning',
            tone: 'funny',
        });

        expect(result).toBeDefined();
        expect(typeof result).toBe('string');
        expect(result.length).toBeGreaterThan(0);
    });

    it('should respect tone parameter', async () => {
        const tones = ['funny', 'sarcastic', 'wholesome', 'dark', 'random'] as const;

        for (const tone of tones) {
            const result = await generateCaption({
                prompt: 'Test prompt',
                tone,
            });

            expect(result).toBeDefined();
            expect(typeof result).toBe('string');
        }
    });

    it('should enforce max length', async () => {
        const result = await generateCaption({
            prompt: 'Very long prompt that should generate a very long caption',
            maxLength: 50,
        });

        expect(result.length).toBeLessThanOrEqual(50);
    });

    it('should handle empty prompts with fallback', async () => {
        const result = await generateCaption({
            prompt: '',
            tone: 'funny',
        });

        expect(result).toBeDefined();
        expect(typeof result).toBe('string');
    });
});
